name: torrent
description: Bittorrent library inplemented in pure Dart.
version: 0.0.1+1
homepage: https://github.com/xtyxtyx/torrent
author: xuty <root@xuty.tk>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  torrent_parser: ^1.2.0
  torrent_bencode: ^0.1.0
  easy_udp: ^1.2.0
  path: ^1.6.0
  ansicolor: ^1.0.0
  base32: ^1.0.0
  collection: ^1.0.0
  logging: ^0.11.0
  async: ^2.3.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
